#!/bin/sh

# ucitrack 只对非 PROCD 程序有效
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@zerotier[-1]
	add ucitrack zerotier
	set ucitrack.@zerotier[-1].init='luci-zerotier'
	commit ucitrack

	delete firewall.zerotier
	set firewall.zerotier=include
	set firewall.zerotier.type=script
	set firewall.zerotier.path='/usr/share/zerotier/firewall.include'
	set firewall.zerotier.reload=1
	commit firewall
EOF

rm -f /tmp/luci-indexcache
exit 0
